# Generated by Django 5.2.6 on 2025-09-09 14:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Room code (e.g., R001)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Room name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(help_text='Maximum capacity of the room', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('min_capacity', models.IntegerField(default=1, help_text='Minimum capacity required', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('maintenance', 'Under Maintenance')], default='open', max_length=20)),
                ('available_from', models.TimeField(default=datetime.time(9, 0), help_text='Available from (e.g., 09:00)')),
                ('available_to', models.TimeField(default=datetime.time(17, 0), help_text='Available until (e.g., 17:00)')),
                ('min_booking_hours', models.IntegerField(default=1, help_text='Minimum booking duration in hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('max_booking_hours', models.IntegerField(default=4, help_text='Maximum booking duration in hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('has_computer', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=True)),
                ('floor_number', models.IntegerField(default=1)),
                ('building', models.CharField(default='Main Building', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Booking date')),
                ('start_time', models.TimeField(help_text='Start time (e.g., 14:00)')),
                ('duration_hours', models.IntegerField(help_text='Duration in hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('purpose', models.CharField(blank=True, help_text='Purpose of booking', max_length=200)),
                ('expected_attendees', models.IntegerField(help_text='Expected number of attendees', validators=[django.core.validators.MinValueValidator(1)])),
                ('special_requirements', models.TextField(blank=True, help_text='Special requirements or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'pending'])), fields=('room', 'date', 'start_time'), name='unique_room_datetime_booking')],
            },
        ),
    ]
